# Generated by Django 6.0.6 on 2026-07-31 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(default=18, help_text='Возраст (не менее 18 лет)', validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
