# Generated by Django 6.0.6 on 2026-07-28 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_user_age_user_country_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(help_text='Возраст (не менее 18 лет)', validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('RU', 'Россия'), ('BE', 'Беларусь'), ('UA', 'Украина'), ('KZ', 'Казахстан'), ('UZ', 'Узбекистан'), ('GE', 'Грузия'), ('AZ', 'Азербайджан'), ('LT', 'Литва'), ('LV', 'Латвия'), ('EE', 'Эстония'), ('AM', 'Армения'), ('TM', 'Туркменистан'), ('KG', 'Киргизия'), ('MD', 'Молдавия'), ('TJ', 'Таджикистан')], default='RU', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1),
        ),
    ]
