# Generated by Django 6.0.6 on 2026-07-31 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automobile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.PositiveIntegerField()),
                ('full_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая цена')),
                ('full_time', models.PositiveIntegerField(verbose_name='Общая продолжительность работ')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='automobile.automobile')),
                ('part', models.ManyToManyField(to='automobile.sparepart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
                ('work', models.ManyToManyField(to='automobile.autowork')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['number', '-created_at'],
            },
        ),
    ]
