# Generated by Django 6.0.6 on 2026-07-29 11:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automobile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая цена')),
                ('full_time', models.DurationField(default=datetime.timedelta(seconds=60), verbose_name='Общая продолжительность работ')),
                ('order_auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='automobile.automobile')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobile.sparepart')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_part',
            field=models.ManyToManyField(through='order.OrderPart', to='automobile.sparepart'),
        ),
        migrations.CreateModel(
            name='OrderWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobile.autowork')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_work',
            field=models.ManyToManyField(through='order.OrderWork', to='automobile.autowork'),
        ),
    ]
