# Generated by Django 6.0.6 on 2026-08-05 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('order', '0001_initial'), ('order', '0002_alter_order_full_time'), ('order', '0003_alter_order_full_time'), ('order', '0004_alter_order_full_time'), ('order', '0005_alter_order_options_remove_order_number_and_more')]

    initial = True

    dependencies = [
        ('automobile', '0001_initial'),
        ('automobile', '0002_rename_vin_number_automobile_vin_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('full_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая цена')),
                ('full_time', models.PositiveIntegerField(default=0, verbose_name='Общая продолжительность работ')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='automobile.automobile')),
                ('part', models.ManyToManyField(to='automobile.sparepart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('work', models.ManyToManyField(to='automobile.autowork')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['id', '-created_at'],
            },
        ),
    ]
