# Generated by Django 6.0.6 on 2026-07-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_time',
            field=models.PositiveIntegerField(null=True, verbose_name='Общая продолжительность работ'),
        ),
    ]
