# Generated by Django 6.0.6 on 2026-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_full_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая продолжительность работ'),
        ),
    ]
