# Generated by Django 6.0.6 on 2026-08-05 16:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('automobile', '0001_initial'), ('automobile', '0002_rename_vin_number_automobile_vin_number_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('brand', models.CharField(max_length=64, verbose_name='Марка')),
                ('model', models.CharField(max_length=64, verbose_name='Модель')),
                ('vin_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^[A-HJ-NR-ZP0-9]*$', 'Только буквенно-цифровые символы, исключая буквы I, O и Q.'), django.core.validators.MinLengthValidator(17, message='VIN должен содержать ровно 17 символов.')], verbose_name='VIN')),
                ('registration_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-ZАВЕКМНОРСТУХ0-9]+$', 'Только буквенно-цифровые символы латинского алфавита или буквы АВЕКМНОРСТУХ русского алфавита.')], verbose_name='Государственный номер')),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбэк'), ('station wagon', 'Универсал'), ('coupe', 'Купе'), ('pickup', 'Пикап'), ('convertible', 'Кабриолет'), ('roadster', 'Родстер'), ('minivan', 'Минивэн'), ('SUV', 'Внедорожник'), ('crossover', 'Кроссовер'), ('limousine', 'Лимузин')], max_length=32, verbose_name='Тип кузова')),
                ('chasses_number', models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^[A-HJ-NR-ZP0-9]*$', 'Только буквенно-цифровые символы, исключая буквы I, O и Q.')])),
                ('body_number', models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^[A-HJ-NR-ZP0-9]*$', 'Только буквенно-цифровые символы, исключая буквы I, O и Q.')])),
                ('colour', models.CharField(max_length=32, verbose_name='Цвет')),
                ('vehicle_passport', models.CharField(unique=True, verbose_name='Паспорт транспортного средства')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Automobile',
                'verbose_name_plural': 'Automobiles',
                'db_table': 'automobiles',
                'ordering': ['-id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Autowork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(max_length=32, verbose_name='Номер работы')),
                ('name', models.CharField(max_length=128, verbose_name='Название работы')),
                ('duration', models.PositiveIntegerField(default=1, verbose_name='Продолжительность работы')),
                ('workshop', models.CharField(choices=[('bodyshop', 'Кузовной'), ('locksmith', 'Слесарный')], default='locksmith', max_length=32, verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Autowork',
                'verbose_name_plural': 'Autoworks',
                'db_table': 'autoworks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=128, verbose_name='Деталь')),
                ('number', models.CharField(max_length=32, verbose_name='Номер детали')),
                ('brand', models.CharField(max_length=64, verbose_name='Производитель')),
                ('image', models.ImageField(upload_to='')),
                ('vendor', models.CharField(max_length=128, verbose_name='Поставщик')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Sparepart',
                'verbose_name_plural': 'Spareparts',
                'db_table': 'spareparts',
                'ordering': ['name'],
            },
        ),
    ]
