# Generated by Django 6.0.6 on 2026-08-05 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobile',
            old_name='VIN_number',
            new_name='vin_number',
        ),
        migrations.AlterField(
            model_name='automobile',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбэк'), ('station wagon', 'Универсал'), ('coupe', 'Купе'), ('pickup', 'Пикап'), ('convertible', 'Кабриолет'), ('roadster', 'Родстер'), ('minivan', 'Минивэн'), ('SUV', 'Внедорожник'), ('crossover', 'Кроссовер'), ('limousine', 'Лимузин')], max_length=32, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='brand',
            field=models.CharField(max_length=64, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='colour',
            field=models.CharField(max_length=32, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='model',
            field=models.CharField(max_length=64, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='vehicle_passport',
            field=models.CharField(unique=True, verbose_name='Паспорт транспортного средства'),
        ),
        migrations.AlterField(
            model_name='autowork',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название работы'),
        ),
        migrations.AlterField(
            model_name='autowork',
            name='number',
            field=models.CharField(max_length=32, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='autowork',
            name='workshop',
            field=models.CharField(choices=[('bodyshop', 'Кузовной'), ('locksmith', 'Слесарный')], default='locksmith', max_length=32, verbose_name='Цех'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='brand',
            field=models.CharField(max_length=64, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Деталь'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='number',
            field=models.CharField(max_length=32, verbose_name='Номер детали'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='vendor',
            field=models.CharField(max_length=128, verbose_name='Поставщик'),
        ),
    ]
