# Generated by Django 6.0.6 on 2026-08-05 17:14

import automobile.validation
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0001_squashed_0002_rename_vin_number_automobile_vin_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='vin_number',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^[A-HJ-NR-ZP0-9]*$', 'Только буквенно-цифровые символы, исключая буквы I, O и Q.'), automobile.validation.validate_vin_length], verbose_name='VIN'),
        ),
    ]
