# Generated by Django 6.0.6 on 2026-09-12 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0004_alter_automobile_body_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбэк'), ('station wagon', 'Универсал'), ('coupe', 'Купе'), ('pickup', 'Пикап'), ('convertible', 'Кабриолет'), ('roadster', 'Родстер'), ('minivan', 'Минивэн'), ('SUV', 'Внедорожник'), ('crossover', 'Кроссовер'), ('limousine', 'Лимузин')], max_length=32, null=True, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='chasses_number',
            field=models.CharField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-HJ-NR-ZP0-9]*$', 'Только буквенно-цифровые символы, исключая буквы I, O и Q.')]),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='colour',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-ZАВЕКМНОРСТУХ0-9]+$', 'Только буквенно-цифровые символы латинского алфавита или буквы АВЕКМНОРСТУХ русского алфавита.')], verbose_name='Государственный номер'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='vehicle_passport',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='Паспорт транспортного средства'),
        ),
    ]
