# Generated by Django 6.0.6 on 2026-09-12 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0005_alter_automobile_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='body_number',
            field=models.CharField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-HJ-NR-ZP0-9]*$', 'Только буквенно-цифровые символы, исключая буквы I, O и Q.')]),
        ),
    ]
